services:
  # 后端服务 - imgcleaner
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imgcleaner-backend
    ports:
      - "8001:8001"
    volumes:
      - ./yolov8s.pt:/app/yolov8s.pt:ro
    restart: unless-stopped

  # 后端服务 - iopaint
  # 2. IOPaint 后端 (复杂消除)
  iopaint:
    image: sanster/iopaint:latest
    container_name: imgcleaner-iopaint
    ports:
      - "8003:8003"
    command: start --port 8003
    volumes:
      # 【强烈建议】: 挂载缓存目录！
      # 否则每次重启它都会重新下载 2GB+ 的模型，且服务器网络大概率下载失败
      - ./cache_iopaint:/root/.cache
    restart: unless-stopped

  # 前端服务
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: imgcleaner-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
